SELECT
    stop_id,
    direction_id,
    stop_name,
    station_name,
    station_descriptive_name,
    map_id as station_id,
    ada,
    red,
    blue,
    g as green,
    brn as brown,
    p as purple,
    pexp as purple_express,
    y as yellow,
    pnk as pink,
    o as orange,
    location.longitude as longitude,
    location.latitude as latitude